baseurl: "https://rjcmarkelz.github.io/"
title: Cody Markelz
theme: ghostwriter
languageCode: en-us
copyright: Cody Markelz
# disqusShortname: XXX
# googleAnalytics: XXX
pygmentsUseClasses: true
# pygmentsCodefences: true
# pygmentsCodefencesGuessSyntax : true
# pygmentsStyle : "monokai"

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Cody Markelz
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Cody Markelz
  description: Professional learner
  github: "https://github.com/rjcmarkelz"
  # gitlab: "https://gitlab.com/XXX"
  linkedin: "https://www.linkedin.com/in/codymarkelz"
  twitter: "https://twitter.com/rjcmarkelz"
  # stackoverflow: "https://stackoverflow.com/users/XXX/YYY"
  # facebook: "https://www.facebook.com/username"
  email: rjcmarkelz@berkeley.edu
  opengraph: true
  shareTwitter: true
  rss: false
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Time Committment:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Projects
      url: /project/
      weight: 2
    - name: Publications
      url: /page/publications/
      weight: 3
    - name: CV
      url: /page/CV/
      weight: 4
    - name: About
      url: /page/about/
      weight: 5
